site:
  title: Netbeheer Nederland Documentation
  url: https://netbeheer-nederland.github.io/docs-dev
content:
  tags: ['v0*']
  branches:  # Disable default branch filter. See: https://gitlab.com/antora/antora/-/issues/268
  sources:
  - url: .
    start_path: ./root_component
    branches: HEAD
    tags:
  - url: https://github.com/Netbeheer-Nederland/doc-documentation-manual
  - url: https://github.com/Netbeheer-Nederland/doc-linkml-guide
  - url: https://github.com/Netbeheer-Nederland/doc-modeling-guide
  - url: https://github.com/Netbeheer-Nederland/dp-meetdata
    start_path: docs-src
  - url: https://github.com/Netbeheer-Nederland/dp-nbl-forecast
    start_path: docs-src
  - url: https://github.com/Netbeheer-Nederland/dp-eh-nettopologie
    start_path: docs-src
  - url: https://github.com/Netbeheer-Nederland/im-capaciteitskaart
    start_path: docs-src
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    kroki-fetch-diagram: true
    kroki-default-format: svg@
  extensions:
  - asciidoctor-kroki
output:
  clean: true
  dir: ./docs
urls:
  latest_version_segment: latest
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
antora:
  extensions:
  - require: '@antora/lunr-extension'
