site:
  title: Netbeheer Nederland Documentation
  url: https://netbeheer-nederland.github.io/docs-dev
content:
  sources:
  - url: .
    start_path: ./root_component
  - url: https://github.com/Netbeheer-Nederland/doc-documentation-manual
  - url: https://github.com/Netbeheer-Nederland/doc-linkml-guide
  - url: https://github.com/Netbeheer-Nederland/doc-modeling-guide
  - url: https://github.com/Netbeheer-Nederland/dp-meetdata
    branches: docs-dev
    start_paths: [v*.*]
  - url: https://github.com/Netbeheer-Nederland/dp-transitietechnieken
    branches: docs-dev
    start_paths: [v*.*]
  - url: https://github.com/Netbeheer-Nederland/dp-netburen
    branches: v*
    start_path: docs-dev
  - url: https://github.com/Netbeheer-Nederland/dp-capaciteitskaart
    branches: v*
    start_path: docs-dev
  - url: https://github.com/Netbeheer-Nederland/dp-nbl-forecast
    branches: v*
    start_path: docs-dev
  #- url: https://github.com/Netbeheer-Nederland/dp-testme
  #  branches: docs-dev
  #  start_paths: [v*.*]
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    kroki-fetch-diagram: true
    kroki-default-format: svg@
    kroki-server-url: http://fruit.ritger.nl:9000
  extensions:
  - asciidoctor-kroki
output:
  clean: true
  dir: ./docs
urls:
  latest_version_segment: latest
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
antora:
  extensions:
  - require: '@antora/lunr-extension'
